//Packaged Food
class Category_27 {
	class FoodCanBakedBeans {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanFrankBeans {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanPasta {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanSardines {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanBeef {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanPotatoes {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanGriff {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanBadguy {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanBoneboy {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanCorn {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanCurgon {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanDemon {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanFraggleos {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanHerpy {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanDerpy {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanOrlok {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanPowell {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanTylers {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanUnlabeled {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanRusUnlabeled {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanRusStew {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanRusPork {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanRusPeas {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanRusMilk {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCanRusCorn {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodChipsSulahoops {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodChipsMysticales {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodChipsChocolate {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCandyChubby {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCandyAnders {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCandyLegacys {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCakeCremeCakeClean {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodCandyMintception {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodPistachio {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodNutmix {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class FoodMRE {type = "trade_items";buy[] = {7000,"worth"};sell[] = {3500,"worth"};};
};

//Cooked Food
class Category_28 {
	class FoodPotatoBaked {type = "trade_items";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};
	class FoodBaconCooked {type = "trade_items";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};
	class FoodBeefCooked {type = "trade_items";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};
	class FoodChickenCooked {type = "trade_items";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};
	class FoodGoatCooked {type = "trade_items";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};
	class FoodMuttonCooked {type = "trade_items";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};
	class FoodDogCooked {type = "trade_items";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};
	class FoodRabbitCooked {type = "trade_items";buy[] = {5000,"worth"};sell[] = {2500,"worth"};};
	// most common
	class FishCookedTrout {type = "trade_items";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	// less common
	class FishCookedSeaBass {type = "trade_items";buy[] = {7000,"worth"};sell[] = {3500,"worth"};};
	// rarest
	class FishCookedTuna {type = "trade_items";buy[] = {9000,"worth"};sell[] = {4500,"worth"};};
};

//Drinks
class Category_29 {
	class ItemWaterBottleUnfilled {type = "trade_items";buy[] = {3000,"worth"};sell[] = {1000,"worth"};};
	class ItemPlasticWaterbottleUnfilled {type = "trade_items";buy[] = {3000,"worth"};sell[] = {1000,"worth"};};	
	class ItemSodaCoke {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaPepsi {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaMdew {type = "trade_items";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class ItemSodaMtngreen {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaR4z0r {type = "trade_items";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class ItemSodaClays {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaSmasht {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaDrwaste {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaFranka {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaLemonade {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaLirik {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaLvg {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaMzly {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaPeppsy {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaRabbit {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaSacrite {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaRocketFuel {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaGrapeDrink {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSherbet {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemSodaRbull {type = "trade_items";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class ItemSodaOrangeSherbet {type = "trade_items";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class ItemWaterBottle {type = "trade_items";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class ItemWaterBottleInfected {type = "trade_items";buy[] = {-1,"worth"};sell[] = {2000,"worth"};};
	class ItemWaterBottleSafe {type = "trade_items";buy[] = {-1,"worth"};sell[] = {2000,"worth"};};
	class ItemWaterBottleBoiled {type = "trade_items";buy[] = {5000,"worth"};sell[] = {250,"worth"};};
	class ItemWaterBottleHerbal {type = "trade_items";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class ItemPlasticWaterBottle {type = "trade_items";buy[] = {-1,"worth"};sell[] = {2000,"worth"};};
	class ItemPlasticWaterBottleInfected {type = "trade_items";buy[] = {-1,"worth"};sell[] = {2000,"worth"};};
	class ItemPlasticWaterBottleSafe {type = "trade_items";buy[] = {-1,"worth"};sell[] = {2000,"worth"};};
	class ItemPlasticWaterBottleBoiled {type = "trade_items";buy[] = {-1,"worth"};sell[] = {3000,"worth"};};
	class ItemPlasticWaterBottleHerbal {type = "trade_items";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};	
};

//Clothes
class Category_30 {
	class Skin_SurvivorW2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};	
	class Skin_SurvivorW3_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};	
	class Skin_SurvivorWpink_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_SurvivorWurban_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_SurvivorWcombat_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_SurvivorWwinter_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_SurvivorWdesert_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};	
	class Skin_DoctorW_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_WorkerW_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_PolicemanW_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_PriestW_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_HookerW1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};	
	class Skin_HookerW2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_HookerW3_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_HookerW4_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_HookerW5_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};	
	class Skin_Functionary1_EP1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Haris_Press_EP1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Priest_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Survivor2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Rocker1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Rocker2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Rocker3_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Rocker4_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_RU_Policeman_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_RU_Policeman2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Pilot_EP1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};	
	class Skin_INS_Lopotev_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Doctor_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Assistant_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Worker1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Worker3_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Worker4_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_TK_CIV_Takistani01_EP1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_TK_CIV_Takistani03_EP1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_TK_CIV_Takistani04_EP1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_TK_CIV_Takistani06_EP1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};	
	class Skin_Firefighter1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Firefighter2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Firefighter3_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Firefighter4_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Firefighter5_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Firefighter_Officer1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Firefighter_Officer2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};	
	class Skin_Postman1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Postman2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Postman3_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Postman4_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Hunter_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Gardener_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_SchoolTeacher_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian3_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian4_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian5_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian6_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian7_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian8_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian9_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian10_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian11_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian12_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian13_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Civilian14_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Prisoner1_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Prisoner2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Prisoner3_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Reporter_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_MafiaBoss_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Dealer_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_BusinessMan_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_INS_Worker2_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Paramedic_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Skin_Garbage_Man_DZ {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
};

//Backpacks
class Category_31 {
	/* New Backpacks */
	class GymBag_Camo_DZE1 {type = "trade_backpacks";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class GymBag_Green_DZE1 {type = "trade_backpacks";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Patrol_Pack_DZE1 {type = "trade_backpacks";buy[] = {3000,"worth"};sell[] = {1500,"worth"};};
	class Czech_Vest_Pouch_DZE1 {type = "trade_backpacks";buy[] = {3000,"worth"};sell[] = {1500,"worth"};};
	class Assault_Pack_DZE1 {type = "trade_backpacks";buy[] = {3000,"worth"};sell[] = {1500,"worth"};};
	class TerminalPack_DZE1 {type = "trade_backpacks";buy[] = {3500,"worth"};sell[] = {1750,"worth"};};
	class TinyPack_DZE1 {type = "trade_backpacks";buy[] = {3000,"worth"};sell[] = {3000,"worth"};};
	class ALICE_Pack_DZE1 {type = "trade_backpacks";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};
	class TK_Assault_Pack_DZE1 {type = "trade_backpacks";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};
	class School_Bag_DZE1 {type = "trade_backpacks";buy[] = {1500,"worth"};sell[] = {750,"worth"};};
	class CompactPack_DZE1 {type = "trade_backpacks";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class British_ACU_DZE1 {type = "trade_backpacks";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};	
	class GunBag_DZE1 {type = "trade_backpacks";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class PartyPack_DZE1 {type = "trade_backpacks";buy[] = {700,"worth"};sell[] = {350,"worth"};};
	class NightPack_DZE1 {type = "trade_backpacks";buy[] = {800,"worth"};sell[] = {400,"worth"};};
	class SurvivorPack_DZE1 {type = "trade_backpacks";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};
	class AirwavesPack_DZE1 {type = "trade_backpacks";buy[] = {12000,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_DZE1 {type = "trade_backpacks";buy[] = {12000,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_Camping_DZE1 {type = "trade_backpacks";buy[] = {-12000,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_OD_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_DES_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_3DES_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_WDL_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_MAR_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_DMAR_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_UCP_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_6DES_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_TAK_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_NVG_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_BLK_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_DPM_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_FIN_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_MTC_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_NOR_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_WIN_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_ATC_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_MTL_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class CzechBackpack_FTN_DZE1 {type = "trade_backpacks";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};	
	class WandererBackpack_DZE1 {type = "trade_backpacks";buy[] = {15000,"worth"};sell[] = {7500,"worth"};};
	class LegendBackpack_DZE1 {type = "trade_backpacks";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class CoyoteBackpack_DZE1 {type = "trade_backpacks";buy[] = {40000,"worth"};sell[] = {20000,"worth"};};
	class CoyoteBackpack_Camping_DZE1 {type = "trade_backpacks";buy[] = {40000,"worth"};sell[] = {20000,"worth"};};
	class CoyoteBackpackDes_DZE1 {type = "trade_backpacks";buy[] = {40000,"worth"};sell[] = {20000,"worth"};};
	class CoyoteBackpackWdl_DZE1 {type = "trade_backpacks";buy[] = {40000,"worth"};sell[] = {20000,"worth"};};
	class LargeGunBag_DZE1 {type = "trade_backpacks";buy[] = {60000,"worth"};sell[] = {30000,"worth"};};
	class LargeGunBag_DZE2 {type = "trade_backpacks";buy[] = {80000,"worth"};sell[] = {40000,"worth"};};
};

//Miscellaneous
class Category_32 {
	class ItemKosmosSmokes {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemTrashPaperMusic {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemTrashPaper {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemCards {type = "trade_items";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class ItemORP {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemARM {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemAVE {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemLRK {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemTNK {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemTruckORP {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemTruckARM {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemTruckAVE {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemTruckLRK {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemTruckTNK {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};		
	class ItemHeliAVE {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemHeliLRK {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};
	class ItemHeliTNK {type = "trade_items";buy[] = {50000,"worth"};sell[] = {25000,"worth"};};	
	class ItemPlotDeed {type = "trade_items";buy[] = {-1,"worth"};sell[] = {95000,"worth"};};
};